fix sensor errors when device off or failed
libdyson-wg/ha-dyson pull request #27
Opened 2023-06-03 16:44 UTC by nhulsch

this is a fix for #16 based on the changes that were made by @Aohzan on the original repository (https://github.com/shenxn/ha-dyson/pull/189)

2023-06-04 18:39 UTC, dotvezz commented
It's _really_ exciting to get PRs from the community after adopting it from shen, thanks for your work! This helps a lot while I've been busy with life the past couple of weeks. 

This looks good to me - I'll do some quick testing with it ASAP and if all seems good I'll get it merged and cut a new release.

2023-06-18 14:34 UTC, dotvezz requested changes
Whew, sorry for the slow review here. And of course thanks for your contribution! I've just got two categories of suggestions here. One is admittedly a nitpick, but the other is likely a bit more important.

1. For all the `int | None` type hints, let's use `Optional[int]` to be idiomatic and consistent with the rest of the (admittedly slow-growing bunch of) hints.
2. In my testing environment, I ran into TypeErrors on the `available` properties. Let's just be a bit more explicit on those checks.

Once that's taken care of, we're good to go!

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +    def native_value(self) -> int | None:
```suggestion
    def native_value(self) -> Optional[int]
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +    _SENSOR_NAME: str | None = None
```suggestion
    _SENSOR_TYPE: Optional[str] = None
    _SENSOR_NAME: Optional[str] = None
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +    def native_value(self) -> float | None:
```suggestion
    def native_value(self) -> Optional[float]:
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +    def native_value(self) -> float | None:
```suggestion
    def native_value(self) -> Optional[float]:
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +    def native_value(self) -> int | None:
```suggestion
    def native_value(self) -> Optional[int]:
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +    def native_value(self) -> int | None:
```suggestion
    def native_value(self) -> Optional[int]:
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +    def native_value(self) -> int | None:
```suggestion
    def native_value(self) -> Optional[int]:
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +    def native_value(self) -> int | None:
```suggestion
    def native_value(self) -> Optional[int]:
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +    def native_value(self) -> int | None:
```suggestion
    def native_value(self) -> Optional[int]:
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +    def native_value(self) -> int | None:
```suggestion
    def native_value(self) -> Optional[int]:
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +        return self._device.time_until_next_clean >= 0
```suggestion
        return isinstance(self._device.time_until_next_clean, (int, float))
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +        return self._device.humidity >= 0
```suggestion
        return isinstance(self._device.humidity, (int, float))
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +        return self._device.temperature >= 0
```suggestion
        return isinstance(self._device.temperature, (int, float))
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +        return self._device.particulate_matter_10 >= 0
```suggestion
        return isinstance(self._device.particulate_matter_10, (int, float))
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +        return self._device.particulates >= 0
```suggestion
        return isinstance(self._device.particulates, (int, float))
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +        return self._device.volatile_organic_compounds >= 0
```suggestion
        return isinstance(self._device.volatile_organic_compounds, (int, float))
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +        return self._device.nitrogen_dioxide >= 0
```suggestion
        return isinstance(self._device.nitrogen_dioxide, (int, float))
```

2023-06-18 14:34 UTC, dotvezz commented on custom_components/dyson_local/sensor.py
> +    def available(self) -> bool:
```suggestion
        return isinstance(self._device.time_until_next_clean, (int, float))
```

2023-06-18 15:27 UTC, nhulsch commented
Feel free to change it directly in your repository. I was just adopting code from a PR on the original repo

2023-06-18 15:27 UTC, closed without merging

2023-07-05 01:16 UTC, dotvezz commented
@nhulsch thanks again for this! I finally got around to updating and releasing it a few days ago. Welcome to the contributors club!

![image](https://github.com/libdyson-wg/ha-dyson/assets/4571263/58a2df72-74fe-45e5-b97d-d649117893a8)